services:
  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: always
    ports:
      - "3386:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: easymanager
      MYSQL_USER: herbert
      MYSQL_PASSWORD: Hs010519#
    networks:
      - springnet

  app:
    build: .
    container_name: springboot-app
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/easymanager
      SPRING_DATASOURCE_USERNAME: herbert
      SPRING_DATASOURCE_PASSWORD: Hs010519
    networks:
      - springnet

networks:
  springnet:
